DROP TABLE IF EXISTS `ai_params`;
CREATE TABLE `ai_params` (
  `npc_id` int(11) unsigned NOT NULL DEFAULT '0',
  `name` varchar(45) DEFAULT NULL,
  `param` varchar(25) NOT NULL DEFAULT '',
  `value` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`npc_id`,`param`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `ai_params` VALUES ('22199', 'Pterosaur', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22215', 'Tiranosaurus', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22216', 'Tiranosaurus', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22217', 'Tiranosaurus', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('32350', 'Sandstorm', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22137', 'Penance Guard', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22138', 'Chapel Guard', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22194', 'Penance Guard', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22327', 'Arcane Scout', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22360', 'Town Patrolman', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18329', 'Hall Keeper Captain', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18330', 'Hall Keeper Wizard', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18331', 'Hall Keeper Guard', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18332', 'Hall Keeper Patrol', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18333', 'Hall Keeper Suicidal Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18334', 'Dark Choir Captain', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18335', 'Dark Choir Prima Donna', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18336', 'Dark Choir Lancer', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18337', 'Dark Choir Archer', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18338', 'Dark Choir Witch Doctor', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18339', 'Dark Choir Player', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18340', 'Hall Keeper Suicidal Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18341', 'Hall Keeper Suicidal Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22536', 'Royal Guard Captain', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22537', 'Dragon Steed Troop Grand Magician', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22538', 'Dragon Steed Troop Commander', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22539', 'Dragon Steed Troops No 1 Battalion Commander', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22540', 'White Dragon Leader', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22541', 'Dragon Steed Troop Infantry', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22542', 'Dragon Steed Troop Magic Leader', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22543', 'Dragon Steed Troop Magician', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22544', 'Dragon Steed Troop Magic Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22546', 'Warrior of Light', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22547', 'Dragon Steed Troop Healer', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22548', 'Dragon Steed Troop Javelin Thrower', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22549', 'Dragon Steed Troop Javelin Thrower', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22596', 'White Dragon Leader', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('29162', 'Soldiers of Bravery', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22708', 'Invader Warrior of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22709', 'Invader Healer of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22710', 'Invader Guide of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22711', 'Invader Destroyer of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22712', 'Invader Assassin of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22713', 'Invader Shaman of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22714', 'Invader Archer of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22715', 'Invader Soldier of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22716', 'Invader Soldier of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22717', 'Invader Disciple of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22718', 'Invader Elite Soldier of Nightmare', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22719', 'Nihil Invader Warrior', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22720', 'Nihil Invader Healer', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22721', 'Nihil Invader Guide', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22722', 'Nihil Invader Destroyer', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22723', 'Nihil Invader Assassin', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22724', 'Nihil Invader Shaman', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22725', 'Nihil Invader Archer', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22726', 'Nihil Invader Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22727', 'Nihil Invader Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22728', 'Nihil Invader Disciple', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22729', 'Nihil Invader Elite Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22730', 'Mutant Warrior', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22731', 'Mutant Healer', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22732', 'Mutant Guide', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22733', 'Mutant Destroyer', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22734', 'Mutant Assassin', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22735', 'Mutant Shaman', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22736', 'Mutant Overlord', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22737', 'Mutant Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22738', 'Mutant Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22739', 'Mutant Disciple', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('22740', 'Mutant Elite Soldier', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('29001', 'Queen Ant', 'MaxPursueRange', '2500');
INSERT INTO `ai_params` VALUES ('29004', 'Guard Ant', 'MaxPursueRange', '3000');
INSERT INTO `ai_params` VALUES ('29005', 'Royal Guard Ant', 'MaxPursueRange', '3000');
INSERT INTO `ai_params` VALUES ('29014', 'Orfen', 'MaxPursueRange', '5000');
INSERT INTO `ai_params` VALUES ('29019', 'Antharas', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29020', 'Baium', 'MaxPursueRange', '20000');
INSERT INTO `ai_params` VALUES ('29022', 'Zaken', 'MaxPursueRange', '20000');
INSERT INTO `ai_params` VALUES ('29028', 'Valakas', 'MaxPursueRange', '50000');
INSERT INTO `ai_params` VALUES ('29065', 'Sailren', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29066', 'Antharas', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29067', 'Antharas', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29068', 'Antharas', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29046', 'Scarlet van Halisha', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29047', 'Scarlet van Halisha', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29048', 'Evil Spirit', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29049', 'Evil Spirit', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29050', 'Breath of Halisha', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29051', 'Breath of Halisha', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29095', 'Gordon', 'MaxPursueRange', '30000');
INSERT INTO `ai_params` VALUES ('29069', 'Behemoth Dragon', 'MaxPursueRange', '10000');
INSERT INTO `ai_params` VALUES ('29070', 'Dragon Bomber', 'MaxPursueRange', '10000');
INSERT INTO `ai_params` VALUES ('29071', 'Dragon Bomber', 'MaxPursueRange', '10000');
INSERT INTO `ai_params` VALUES ('29072', 'Dragon Bomber', 'MaxPursueRange', '10000');
INSERT INTO `ai_params` VALUES ('29073', 'Dragon Bomber', 'MaxPursueRange', '10000');
INSERT INTO `ai_params` VALUES ('29074', 'Dragon Bomber', 'MaxPursueRange', '10000');
INSERT INTO `ai_params` VALUES ('29075', 'Dragon Bomber', 'MaxPursueRange', '10000');
INSERT INTO `ai_params` VALUES ('29076', 'Dragon Bomber', 'MaxPursueRange', '10000');
INSERT INTO `ai_params` VALUES ('25534', 'Tears', 'MaxPursueRange', '1000');
INSERT INTO `ai_params` VALUES ('25532', 'Kechi', 'MaxPursueRange', '1000');
INSERT INTO `ai_params` VALUES ('25531', 'Darnel', 'MaxPursueRange', '1000');
INSERT INTO `ai_params` VALUES ('18339', 'Dark Choir Player', 'MaxPursueRange', '500');
INSERT INTO `ai_params` VALUES ('29162', 'Soldiers of Bravery', 'MaxPursueRange', '3000');
INSERT INTO `ai_params` VALUES ('29163', 'Tiat', 'MaxPursueRange', '3000');
INSERT INTO `ai_params` VALUES ('25665', 'Yehan Klodekus', 'MaxPursueRange', '1500');
INSERT INTO `ai_params` VALUES ('25666', 'Yehan Klanikus', 'MaxPursueRange', '1500');
INSERT INTO `ai_params` VALUES ('29002', 'Queen Ant Larva', 'ParalizeOnAttack', '10');
INSERT INTO `ai_params` VALUES ('29003', 'Nurse Ant', 'ParalizeOnAttack', '13');
INSERT INTO `ai_params` VALUES ('29004', 'Guard Ant', 'ParalizeOnAttack', '11');
INSERT INTO `ai_params` VALUES ('29005', 'Royal Guard Ant', 'ParalizeOnAttack', '9');
INSERT INTO `ai_params` VALUES ('29015', 'Raikel', 'ParalizeOnAttack', '10');
INSERT INTO `ai_params` VALUES ('29017', 'Riba', 'ParalizeOnAttack', '10');
INSERT INTO `ai_params` VALUES ('29018', 'Riba Iren', 'ParalizeOnAttack', '9');
INSERT INTO `ai_params` VALUES ('29014', 'Orfen', 'FactionNotifyInterval', '1000');
INSERT INTO `ai_params` VALUES ('29015', 'Raikel', 'FactionNotifyInterval', '1000');
INSERT INTO `ai_params` VALUES ('29016', 'Raikel Leos', 'FactionNotifyInterval', '1000');
INSERT INTO `ai_params` VALUES ('29017', 'Riba', 'FactionNotifyInterval', '1000');
INSERT INTO `ai_params` VALUES ('29018', 'Riba Iren', 'FactionNotifyInterval', '1000');
INSERT INTO `ai_params` VALUES ('22142', 'Triols Layperson', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22143', 'Triols Believer', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18344', 'Ancient Egg', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18345', 'Sprigant', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18346', 'Sprigant', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('29006', 'Core', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18371', 'Beleth Sample', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18372', 'Beleth Sample', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18373', 'Beleth Sample', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18374', 'Beleth Sample', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18375', 'Beleth Sample', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18376', 'Beleth Sample', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18377', 'Beleth Sample', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('29100', 'Crystal Prison Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18367', 'Prison Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18368', 'Prison Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22485', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22486', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22487', 'Lost Beholder', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22488', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22489', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22490', 'Lost Beholder', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22491', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22492', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22493', 'Lost Beholder', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22494', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22495', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22496', 'Lost Beholder', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22497', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22498', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22499', 'Lost Beholder', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22500', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22501', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22502', 'Lost Beholder', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22503', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22504', 'Lost Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22505', 'Lost Beholder', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('25616', 'Lost Warden', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('25617', 'Lost Warden', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('25618', 'Lost Warden', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('25619', 'Lost Warden', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('25620', 'Lost Warden', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('25621', 'Lost Warden', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('25622', 'Lost Warden', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22309', 'Kechis Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22310', 'Kechis Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22417', 'Kechis Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('32492', 'Crystal Water Bottle', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('32493', 'Burning Brazier', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22536', 'Royal Guard Captain', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22537', 'Dragon Steed Troop Grand Magician', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22538', 'Dragon Steed Troop Commander', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22539', 'Dragon Steed Troops No 1 Battalion Commander', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22540', 'White Dragon Leader', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22541', 'Dragon Steed Troop Infantry', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22542', 'Dragon Steed Troop Magic Leader', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22543', 'Dragon Steed Troop Magician', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22544', 'Dragon Steed Troop Magic Soldier', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22546', 'Warrior of Light', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22547', 'Dragon Steed Troop Healer', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22548', 'Dragon Steed Troop Javelin Thrower', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22549', 'Dragon Steed Troop Javelin Thrower', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('22596', 'White Dragon Leader', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('29162', 'Soldiers of Bravery', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18635', 'Varka Silenos Recruit', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18636', 'Varka Silenos Footman', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18638', 'Varka Silenos Scout', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18639', 'Varka Silenos Hunter', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18640', 'Varka Silenos Shaman', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18641', 'Varka Silenos Priest', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18642', 'Varka Silenos Warrior', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18644', 'Varka Silenos Medium', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18645', 'Varka Silenos Magus', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18646', 'Varka Silenos Officer', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18648', 'Varka Silenos Seer', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18649', 'Varka Silenos Great Magus', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18650', 'Varka Silenos General', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18652', 'Varka Silenos Great Seer', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18653', 'Varka\'s Elite Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18654', 'Varka\'s Commander', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18655', 'Varka\'s Head Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18656', 'Varka\'s Head Magus', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18657', 'Prophet Guard', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18658', 'Disciple of Prophet', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18659', 'Varka\'s Prophet', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('25690', 'Aenkinel', 'noRandomWalk', 'false');
INSERT INTO `ai_params` VALUES ('25691', 'Aenkinel', 'noRandomWalk', 'false');
INSERT INTO `ai_params` VALUES ('25692', 'Aenkinel', 'noRandomWalk', 'false');
INSERT INTO `ai_params` VALUES ('25693', 'Aenkinel', 'noRandomWalk', 'false');
INSERT INTO `ai_params` VALUES ('25694', 'Aenkinel', 'noRandomWalk', 'false');
INSERT INTO `ai_params` VALUES ('25695', 'Aenkinel', 'noRandomWalk', 'false');
INSERT INTO `ai_params` VALUES ('29095', 'Gordon', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('25126', 'Longhorn Golkonda', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29020', 'Baium', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29065', 'Sailren', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29066', 'Antharas', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29067', 'Antharas', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29068', 'Antharas', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29019', 'Antharas', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29028', 'Valakas', 'isMadness', '30');
INSERT INTO `ai_params` VALUES ('29014', 'Orfen', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29022', 'Zaken', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29046', 'Scarlet van Halisha', 'isMadness', '30');
INSERT INTO `ai_params` VALUES ('29047', 'Scarlet van Halisha', 'isMadness', '30');
INSERT INTO `ai_params` VALUES ('25523', 'Plague Golem', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29099', 'Baylor', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29103', 'Baylor', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('25305', 'Ketra\'s Chief Brakki', 'isMadness', '15');
INSERT INTO `ai_params` VALUES ('29095', 'Gordon', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('25126', 'Longhorn Golkonda', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29020', 'Baium', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29065', 'Sailren', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29066', 'Antharas', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29067', 'Antharas', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29068', 'Antharas', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29019', 'Antharas', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29028', 'Valakas', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29014', 'Orfen', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29022', 'Zaken', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29046', 'Scarlet van Halisha', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29047', 'Scarlet van Halisha', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('25523', 'Plague Golem', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29099', 'Baylor', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29103', 'Baylor', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('25305', 'Ketra\'s Chief Brakki', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('29100', 'Crystal Prison Guard', 'SelfAggressive', '0');
INSERT INTO `ai_params` VALUES ('22270', 'Water Dragon Detractor', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('22271', 'Water Dragon Detractor', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18329', 'Hall Keeper Captain', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18330', 'Hall Keeper Wizard', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18331', 'Hall Keeper Guard', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18332', 'Hall Keeper Patrol', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18333', 'Hall Keeper Suicidal Soldier', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18334', 'Dark Choir Captain', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18335', 'Dark Choir Prima Donna', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18336', 'Dark Choir Lancer', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18337', 'Dark Choir Archer', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18338', 'Dark Choir Witch Doctor', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18339', 'Dark Choir Player', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18340', 'Hall Keeper Suicidal Soldier', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('18341', 'Hall Keeper Suicidal Soldier', 'SelfAggressive', '100');
INSERT INTO `ai_params` VALUES ('13148', 'Lindvior', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18684', 'Red Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18685', 'Red Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18686', 'Red Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18687', 'Blue Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18688', 'Blue Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18689', 'Blue Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18690', 'Green Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18691', 'Green Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('18692', 'Green Star Stone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22602', 'Mutant - Bird', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22603', 'Mutant - Bird', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22604', 'Dra Hawk', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22605', 'Dra Hawk', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22606', 'Floating Skull', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22607', 'Floating Skull', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22608', 'Floating Zombie', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22609', 'Floating Zombie', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22610', 'Mutated Drake Wing', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22611', 'Mutated Drake Wing', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22612', 'Drak', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22613', 'Drak', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22614', 'Vulture Rider', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22615', 'Vulture Rider', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('22616', 'Seed of Pain', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25623', 'Valdstone', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25624', 'Rok', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25625', 'Enira', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25626', 'Dius', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25627', 'Mutant Bird', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25628', 'Dra Hawk', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25629', 'Floating Skull', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25630', 'Floating Zombie', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25631', 'Drake Wing', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25632', 'Drak', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('25633', 'Elite Rider', 'isFlying', 'true');
INSERT INTO `ai_params` VALUES ('21527', 'Anger of Splendor', 'transformOnUnderAttack', '21528');
INSERT INTO `ai_params` VALUES ('21533', 'Alliance of Splendor', 'transformOnUnderAttack', '21534');
INSERT INTO `ai_params` VALUES ('21524', 'Blade of Splendor', 'transformOnUnderAttack', '21525');
INSERT INTO `ai_params` VALUES ('21521', 'Claws of Splendor', 'transformOnUnderAttack', '21522');
INSERT INTO `ai_params` VALUES ('21537', 'Fang of Splendor', 'transformOnUnderAttack', '21538');
INSERT INTO `ai_params` VALUES ('21539', 'Wailing of Splendor', 'transformOnUnderAttack', '21540');
INSERT INTO `ai_params` VALUES ('20830', 'Guardian Angel', 'transformOnDead', '20859');
INSERT INTO `ai_params` VALUES ('21067', 'Guardian Archangel', 'transformOnDead', '21068');
INSERT INTO `ai_params` VALUES ('21062', 'Messenger Angel', 'transformOnDead', '21063');
INSERT INTO `ai_params` VALUES ('20831', 'Seal Angel', 'transformOnDead', '20860');
INSERT INTO `ai_params` VALUES ('21070', 'Seal Archangel', 'transformOnDead', '21071');
INSERT INTO `ai_params` VALUES ('22536', 'Royal Guard Captain', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22536', 'Royal Guard Captain', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22537', 'Dragon Steed Troop Grand Magician', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22537', 'Dragon Steed Troop Grand Magician', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22538', 'Dragon Steed Troop Commander', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22538', 'Dragon Steed Troop Commander', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22539', 'Dragon Steed Troops No 1 Battalion Commander', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22539', 'Dragon Steed Troops No 1 Battalion Commander', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22540', 'White Dragon Leader', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22540', 'White Dragon Leader', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22541', 'Dragon Steed Troop Infantry', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22541', 'Dragon Steed Troop Infantry', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22542', 'Dragon Steed Troop Magic Leader', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22542', 'Dragon Steed Troop Magic Leader', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22543', 'Dragon Steed Troop Magician', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22543', 'Dragon Steed Troop Magician', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22544', 'Dragon Steed Troop Magic Soldier', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22544', 'Dragon Steed Troop Magic Soldier', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22546', 'Warrior of Light', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22546', 'Warrior of Light', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22547', 'Dragon Steed Troop Healer', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22547', 'Dragon Steed Troop Healer', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22548', 'Dragon Steed Troop Javelin Thrower', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22548', 'Dragon Steed Troop Javelin Thrower', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22549', 'Dragon Steed Troop Javelin Thrower', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22549', 'Dragon Steed Troop Javelin Thrower', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22550', 'Savage Warrior', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22550', 'Savage Warrior', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22551', 'Priest of Darkness', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22551', 'Priest of Darkness', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('22552', 'Mutation Drake', 'transformOnDead', '22545');
INSERT INTO `ai_params` VALUES ('22552', 'Mutation Drake', 'transformChance', '3');
INSERT INTO `ai_params` VALUES ('21258', 'Fallen Orc Shaman', 'transformOnUnderAttack', '21259');
INSERT INTO `ai_params` VALUES ('21258', 'Fallen Orc Shaman', 'transformChance', '100');
INSERT INTO `ai_params` VALUES ('30452', 'Kurt', 'evilGuard', 'true');
INSERT INTO `ai_params` VALUES ('30452', 'Kurt', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('30675', 'Corpse Of Kamur', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('30761', 'Corpse Of Fritz', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('30762', 'Corpse Of Lutz', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('30763', 'Corpse Of Kurtz', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('30980', 'Ark Guardian\'s Corpse', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('31074', 'Corpse of Hutaku', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('31665', 'Corpse of Dwarf', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('31752', 'Corpse of Angel', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('32015', 'Scout\'s Corpse', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('32306', 'Native\'s Corpse', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('32528', 'Medibal\'s Corpse', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('32568', 'Unidentified Body', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('32619', '', 'randomAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('20965', 'Chimera Piece', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('20966', 'Changed Creation', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('20967', 'Past Creature', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('20968', 'Nonexistent Man', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('20969', 'Giant\'s Shadow', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('20970', 'Soldier of Ancient Times', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('20971', 'Warrior of Ancient Times', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('20972', 'Shaman of Ancient Times', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('20973', 'Forgotten Ancient People', 'searchingMaster', 'true');
INSERT INTO `ai_params` VALUES ('22536', 'Royal Guard Captain', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22537', 'Dragon Steed Troop Grand Magician', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22538', 'Dragon Steed Troop Commander', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22539', 'Dragon Steed Troops No 1 Battalion Commander', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22540', 'White Dragon Leader', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22541', 'Dragon Steed Troop Infantry', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22542', 'Dragon Steed Troop Magic Leader', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22543', 'Dragon Steed Troop Magician', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22544', 'Dragon Steed Troop Magic Soldier', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22546', 'Warrior of Light', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22547', 'Dragon Steed Troop Healer', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22548', 'Dragon Steed Troop Javelin Thrower', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22549', 'Dragon Steed Troop Javelin Thrower', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22550', 'Savage Warrior', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22551', 'Priest of Darkness', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22552', 'Mutation Drake', 'spawnAnimationDisabled', 'true');
INSERT INTO `ai_params` VALUES ('31710', 'Ketra Van Commander', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('31711', 'Ketra Van Shaman', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('31712', 'Varka Raider', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('13002', 'Life Control Tower', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('13003', 'Life Control Tower', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('13004', 'Flame Control Tower', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('13005', 'Flame Control Tower', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('18705', 'Destroyed Tumor', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('13193', '', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('22340', 'Sandstorm', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('13160', 'Snowman', 'chatWindowDisabled', 'true');
INSERT INTO `ai_params` VALUES ('18601', 'Kratei\'s Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('18602', 'Kratei\'s Watcher', 'noRandomWalk', 'true');
INSERT INTO `ai_params` VALUES ('27347', 'Guards of the Dawn Oracle', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27351', 'Guards of the Dawn', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27348', 'Guards of the Dawn Oracle', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27349', 'Guards of the Dawn Oracle', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27350', 'Guards of the Dawn Oracle', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27352', 'Guards of the Dawn Oracle', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27371', 'Lilim Butcher', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27372', 'Lilim Magus', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27373', 'Lilim Slave Knight', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27374', 'Shilen\'s Evil Thoughts', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27375', 'Shilen\'s Evil Thoughts', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27376', 'Lilim Knight', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('27377', 'Lilim Assassin', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18834', 'Guards of the Dawn', 'canSeeInSilentMove', 'true');
INSERT INTO `ai_params` VALUES ('18835', 'Guards of the Dawn', 'canSeeInSilentMove', 'true');

